# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: macOS-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: |
      curl -O https://tools.veracode.com/integrations/xcode/com.veracode.mobileapplicationpackager.dmg
      echo $?
      mkdir packager
      echo $?
      7z x -opackager com.veracode.mobileapplicationpackager.dmg
      echo $?
      
      #hdiutil mount com.veracode.mobileapplicationpackager.dmg
      
      cd "packager/Veracode Mobile Application Packager/Veracode Mobile Application Packager.app/Contents/SharedSupport"
      echo $?
      
      #pwd; ls
      
      # Package the .xcarchive folder and place in artifact staging
      
      chmod 777 ./vcxcodepkg
      echo $?
      
      ./vcxcodepkg --help
      echo $?
      