# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
pool:
  name: Default
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Test'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'vera_Azure'
    veracodeAppProfile: 'Azure'
    version: '$(build.buildNumber)'
    filepath: 'app/target/verademo.war'
    # optargs: '-autoscan false ' 
    createProfile: true
    importResults: true
    failBuildIfUploadAndScanBuildStepFails: false
    maximumWaitTime: '60'

#steps:
#- task: PowerShell@2
#  displayName: 'Veracode SCA scan'
#  env: {SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)}
#  inputs:
#   targetType: 'inline'
#   script: |
#    Set-ExecutionPolicy AllSigned -Scope Process -Force
#    $ProgressPreference = "SilentlyContinue"
#    iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
#    srcclr scan $(Build.SourcesDirectory) --update-advisor

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: 'Invoke-WebRequest -Uri "https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip" -OutFile pipeline-scan.zip'
#- task: Veracode@3
#  inputs:
#    ConnectionDetailsSelection: 'Endpoint'
#    AnalysisService: 'Veracode'
#    veracodeAppProfile: '$(system.teamProject)'
#    version: '$(build.buildNumber)'
#    filepath: 'pipeline-scan.zip'
#    maximumWaitTime: '360'