# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: SAST Scan

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package
        
    - name: Veracode Upload And Scan
      image: veracode/veracode/api-wrapper-java:latest
      run: | 
        java -jar /opt/veracode/api-wrapper.jar \
        -vid ${{ secrets.VERACODE_API_ID }} \
        -vkey ${{ secrets.VERACODE_API_KEY }} \
        -action UploadAndScan \
        -createprofile false \
        -appname Verademo GitHub \
        -version ${{ github.run_id }} \
        -filepath target/verademo.war 
