name: Veracode Static Analysis Pipeline Scan
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build with Maven
      run: mvn package
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
           args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      
    - name: Unzip the Pipeline Scanner
      run: unzip pipeline-scan-LATEST.zip
    - name: Run Pipeline Scanner
      id: pipeline-scan
      continue-on-error: true
    - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file  target/verademo.war
    
