# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
       java-version: '11'
       distribution: 'adopt'
       server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
       settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build with Maven
      run: mvn package

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{secrets.VERACODE_API_ID}}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        cat secrets.txt
        
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"

    - name: Uncover secret
      run: echo -n "${{secrets.VERACODE_API_ID}}" >> foo && cut -c1-9 foo && cut -c4
      
    - name: Dump secret
      run: echo -n "${{secrets.VERACODE_API_ID}}" | xxd -ps
      

        
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
#  - name: pipeline-scan action step
#      id: pipeline-scan
#      uses: veracode/Veracode-pipeline-scan-action@v1.0.10
#      with:
#          vid: ${{secrets.VERACODE_API_ID}}
#          vkey: ${{secrets.VERACODE_API_KEY}}
#          file: target/verademo.war 
#          veracode_policy_name: "Testing Policy"
         # request_policy: "Veracode Recommended Very High COPY"
         # policy_file: "Veracode Recommended Very High COPY"
         # veracode_policy_name: "Veracode Recommended High"
 #         fail_build: true
          
          
      
