name: SAST Scan with manual
env:
  V_ID: ${{ secrets.VERACODE_API_ID }}
  V_KEY: ${{ secrets.VERACODE_API_KEY }}
  
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}


    - name: veracode
      run: |
          java -jar VeracodeJavaAPI.jar -action uploadandscan -filepath app/target/verademo.war -vid '${ { secrets.VERACODE_API_ID } }' -vkey '${ { secrets.VERACODE_API_KEY } }' -version '${ { github.run_number } }' -autoscan true -appname GITHUB -createprofile true -deleteincompletescan 2 -scantimeout 60 
