# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: SAST Scan

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package
        
    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@master
      with:
        appname: Verademo GitHub
        createprofile: true
        createsandbox: true
        canjobfail: true
        version: ${{ github.run_id }}
        filepath: target/
        sandboxname: Github-Sandbox
        debug: true
        vid: ${{secrets.VERACODE_API_ID}}
        vkey: ${{secrets.VERACODE_API_KEY}}
        
    - name: Fetch Veracode Report
      env:
          VERACODE_API_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_SECRET: '${{ secrets.VERACODE_API_SECRET }}'
      run: |
        git clone https://github.com/veracode/veracode-python-hmac-example.git
        pip install -r veracode-python-hmac-example/requirements.txt
        export VERACODE_API_KEY_ID=${{ env.VERACODE_API_ID}}
        export VERACODE_API_KEY_SECRET=${{ env.VERACODE_API_ID}}
        ID="1845628"
        SANDBOX_ID="5655734"
        
        http --auth-type veracode_hmac GET "https://analysiscenter.veracode.com/api/5.0/getbuildlist.do?app_id=$ID&sandbox_id=$SANDBOX_ID"


        
      
