# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: SAST Scan
env:
  V_ID: ${{ secrets.VERACODE_API_ID }}
  V_KEY: ${{ secrets.VERACODE_API_KEY }}
  
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build with Maven
      run: mvn package
      
    - name: Setup Python for Report Fetching
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@master
      with:
        appname: Verademo GitHub
        createprofile: true
        createsandbox: true
        canjobfail: true
        version: ${{ github.run_id }}
        filepath: target/verademo.war
        sandboxname: Github-Sandbox
        debug: true
        vid: ${{secrets.VERACODE_API_ID}}
        vkey: ${{secrets.VERACODE_API_KEY}}

    - name: Fetch Veracode Report
      run: |
        git clone https://github.com/veracode/veracode-python-hmac-example.git
        pip install -r veracode-python-hmac-example/requirements.txt
        export VERACODE_API_KEY_ID=${{ env.V_ID}}
        export VERACODE_API_KEY_SECRET=${{ env.V_KEY}}
        ID="1845628"
        SANDBOX_ID="5655734"
        
        http --auth-type veracode_hmac GET "https://analysiscenter.veracode.com/api/5.0/getbuildlist.do?app_id=$ID&sandbox_id=$SANDBOX_ID"
  



